### ISSUE TITLE
Setup environment

### ISSUE THREAD

**Issue by webwebweb5** [Vee-Sorawee/Ghum-Restaurant-5th#1]
1. Install node

modules:
- express
- body-parser
- lodash
- axios
- nodemon

2. Create the essential files/folders.

3. .gitignore

4. readme.md

**Comment by Vee-Sorawee** [comment]
f5b50fee3452d49c55eb6128e54460e8493a29cd

**Comment by veevism** [comment]
9ee4be92e622ff3a11967056b1aa0c8fe17c068f
