### ISSUE TITLE
Add menu json

### ISSUE THREAD

**Issue by webwebweb5** [Vee-Sorawee/Ghum-Restaurant-5th#5]
Each menu contains -> 

- id
- title
- category
- price
- img
- desc
- quantity.

Example:
{
    id: 0,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    quantity: 0,
}

**Comment by veevism** [comment]
bad5439e9654ca29b38210579f05d814b8299709

**Comment by veevism** [comment]
bad5439e9654ca29b38210579f05d814b8299709
